In [30]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [31]:
df = pd.read_csv("/content/breast_cancer_data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [32]:
df.shape

(569, 33)

In [33]:
df.drop(columns=['id','Unnamed: 32'],axis=1,inplace=True)

In [34]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

#### test_train_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=0)

#### scaling

In [36]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]])

In [38]:
y_train

338    B
427    B
406    B
96     B
490    B
      ..
277    M
9      M
359    B
192    B
559    B
Name: diagnosis, Length: 455, dtype: object

#### Label encoding

In [39]:
lb = LabelEncoder()
y_train = lb.fit_transform(y_test)
y_test = lb.transform(y_test)

In [40]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

#### numpy arrays to torch tensors

In [41]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [42]:
X_train_tensor

tensor([[-1.1504, -0.3906, -1.1286,  ..., -0.7580, -0.0161, -0.3850],
        [-0.9380,  0.6805, -0.9482,  ..., -0.6069,  0.0967, -0.3862],
        [ 0.5741, -1.0333,  0.5139,  ..., -0.0237, -0.2005, -0.7514],
        ...,
        [-1.3242, -0.2005, -1.3175,  ..., -0.9797, -0.7154, -0.1198],
        [-1.2438, -0.2246, -1.2801,  ..., -1.7540, -1.5816, -1.0060],
        [-0.7369,  1.1499, -0.7123,  ..., -0.2746, -1.2590,  0.2152]],
       dtype=torch.float64)

In [43]:
X_train_tensor.shape

torch.Size([455, 30])

In [44]:
y_train_tensor.shape

torch.Size([114])

#### defining the model

In [55]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self ,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    # calculate loss
    loss = - (y_train_tensor * torch.log(y_pred) +(1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


#### important parameters

In [57]:
learning_rate = 0.1
epochs = 25

#### training pipeline

In [58]:
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # calculate loss
  loss = model.loss_function(y_pred,y_train_tensor)
  print(f'Epoch: {epoch + 1} , loss: {loss.item()}')

  # backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gardients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1} , loss: {loss.item()}')

Epoch: 1 , loss: 3.0616431712662724
Epoch: 1 , loss: 3.0616431712662724
Epoch: 2 , loss: 2.9180133253351284
Epoch: 2 , loss: 2.9180133253351284
Epoch: 3 , loss: 2.7713010132034013
Epoch: 3 , loss: 2.7713010132034013
Epoch: 4 , loss: 2.6223165678200466
Epoch: 4 , loss: 2.6223165678200466
Epoch: 5 , loss: 2.4702586554508055
Epoch: 5 , loss: 2.4702586554508055
Epoch: 6 , loss: 2.314718933120644
Epoch: 6 , loss: 2.314718933120644
Epoch: 7 , loss: 2.1553117727194877
Epoch: 7 , loss: 2.1553117727194877
Epoch: 8 , loss: 1.9926042441564833
Epoch: 8 , loss: 1.9926042441564833
Epoch: 9 , loss: 1.8334434723455117
Epoch: 9 , loss: 1.8334434723455117
Epoch: 10 , loss: 1.6788583201613752
Epoch: 10 , loss: 1.6788583201613752
Epoch: 11 , loss: 1.5291839142315415
Epoch: 11 , loss: 1.5291839142315415
Epoch: 12 , loss: 1.3891700172229966
Epoch: 12 , loss: 1.3891700172229966
Epoch: 13 , loss: 1.2630124658317874
Epoch: 13 , loss: 1.2630124658317874
Epoch: 14 , loss: 1.1524337909223783
Epoch: 14 , loss: 1.1

In [59]:
model.weights

tensor([[ 0.0295],
        [-0.1674],
        [-0.2041],
        [ 0.3342],
        [-0.2501],
        [ 0.2657],
        [ 0.2013],
        [-0.4232],
        [ 0.2811],
        [ 0.2025],
        [ 0.5406],
        [ 0.0197],
        [-0.3241],
        [-0.1325],
        [ 0.0908],
        [ 0.0693],
        [-0.0453],
        [-0.0853],
        [ 0.1341],
        [ 0.0825],
        [ 0.3231],
        [ 0.3627],
        [-0.2786],
        [-0.0368],
        [-0.1979],
        [ 0.0285],
        [-0.0731],
        [-0.1454],
        [-0.2303],
        [ 0.2068]], dtype=torch.float64, requires_grad=True)

In [60]:
model.bias

tensor([-0.0749], dtype=torch.float64, requires_grad=True)

#### Evaluation

In [63]:
# Model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy.item()}')

Accuracy : 0.5707910060882568
