## Intro of nn module

#### structure 1 : 5 inputs and single output

In [1]:

# Create basic model class

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) # it'll work but below is recommended approach bcz of overriding of __Call__
model(features)

tensor([[0.5005],
        [0.4544],
        [0.4047],
        [0.4412],
        [0.4581],
        [0.4694],
        [0.4410],
        [0.4523],
        [0.4822],
        [0.5200]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights

model.linear.weight

Parameter containing:
tensor([[-0.2363,  0.0109, -0.4421,  0.3692,  0.3962]], requires_grad=True)

In [4]:
# show model bias

model.linear.bias

Parameter containing:
tensor([-0.0642], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### structure 2 : input layer(5),relu,hidden(3),sigmoid ,output(1)

In [7]:
class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [8]:
# create dataset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) # it'll work but below is recommended approach bcz of overriding of __Call__
model(features)

tensor([[0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349],
        [0.5349]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear1.weight

Parameter containing:
tensor([[-0.4183,  0.3572,  0.0272,  0.0940, -0.3940],
        [-0.0403, -0.0643, -0.1404, -0.3471,  0.3324],
        [ 0.1794, -0.4138, -0.1330, -0.1895, -0.2390]], requires_grad=True)

In [11]:
model.linear1.bias

Parameter containing:
tensor([-0.3809, -0.0968, -0.1436], requires_grad=True)

In [12]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### simplified code for above architecture

In [20]:
class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)

    return out

In [21]:
# create dataset

features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

# forward pass

model(features)

tensor([[0.6332],
        [0.6202],
        [0.6183],
        [0.6202],
        [0.6043],
        [0.6122],
        [0.6271],
        [0.6311],
        [0.6245],
        [0.6043]], grad_fn=<SigmoidBackward0>)

In [22]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00