In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not availabe.currently using CPU")

GPU not availabe.currently using CPU


# Creating tensor

In [3]:
# using empty

a = torch.empty(2,3)
a

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.9333e+15, 4.3370e-41]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand

torch.rand(2,3)

tensor([[0.2787, 0.1451, 0.4027],
        [0.5032, 0.7639, 0.4009]])

In [8]:
torch.rand(2,3)

tensor([[0.5734, 0.3762, 0.2246],
        [0.9100, 0.5544, 0.8572]])

In [9]:
# using manual seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:

torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#  other ways

# using arange

print("using arange : ",torch.arange(0,10,2))

# using linspace

print("using linspace : ",torch.linspace(0,10,10))

# using eye

print("using eye : ", torch.eye(5))

# using full

print("uing full : ",torch.full((3,3),5))


using arange :  tensor([0, 2, 4, 6, 8])
using linspace :  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
uing full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
x.shape

torch.Size([3, 3])

In [17]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [25]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

# Tensor Data Types

In [21]:
# find data type

x.dtype

torch.int64

In [22]:
# assign data type

torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

# Mathematical operations

#### 1. Scaler operations

In [27]:

x = torch.rand(2,2)
x

tensor([[0.9014, 0.9969],
        [0.7565, 0.2239]])

In [31]:
# addition
print(x+2)

# substraction
print(x-2)

# multiplication
print(x*2)

# division
print(x/3)

# int division
print((x*100)//3)
# mod
print(((x*100)//3)%2)

# power
print(x**2)


tensor([[2.9014, 2.9969],
        [2.7565, 2.2239]])
tensor([[-1.0986, -1.0031],
        [-1.2435, -1.7761]])
tensor([[1.8028, 1.9938],
        [1.5130, 0.4478]])
tensor([[0.3005, 0.3323],
        [0.2522, 0.0746]])
tensor([[30., 33.],
        [25.,  7.]])
tensor([[0., 1.],
        [1., 1.]])
tensor([[0.8125, 0.9938],
        [0.5723, 0.0501]])


#### 2.Element wise operations

In [29]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [30]:
print(a)
print(b)

tensor([[0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440]])
tensor([[0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277]])


In [32]:
# add
print(a+b)

# substract
print(a-b)

# multiplication
print(a*b)

# division
print(a/b)

# power

print(a**b)

# mod
print(a%b)

tensor([[1.2502, 0.9229, 1.3130],
        [0.7983, 1.6774, 0.9717]])
tensor([[-0.6455, -0.5661,  0.3346],
        [ 0.3132,  0.2767, -0.0837]])
tensor([[0.2866, 0.1328, 0.4030],
        [0.1348, 0.6842, 0.2343]])
tensor([[0.3190, 0.2397, 1.6841],
        [2.2912, 1.3951, 0.8415]])
tensor([[0.3218, 0.2771, 0.9096],
        [0.8672, 0.9839, 0.6515]])
tensor([[0.3023, 0.1784, 0.3346],
        [0.0706, 0.2767, 0.4440]])


In [33]:
c = torch.tensor([1,-2,3,-4])

In [34]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [35]:
# negative

torch.neg(c)

tensor([-1,  2, -3,  4])

In [36]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [37]:
# round

torch.round(d)

tensor([2., 2., 4., 4.])

In [38]:
# ceil

torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
# floor

torch.floor(d)

tensor([1., 2., 3., 4.])

In [40]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#### 3. Reduction operation

In [45]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[9., 4., 0.],
        [5., 7., 5.]])

In [46]:
# sum

print(torch.sum(e))

# sum along columns

print(torch.sum(e,dim=0))

# sum along rows

print(torch.sum(e,dim=1))

tensor(30.)
tensor([14., 11.,  5.])
tensor([13., 17.])


In [47]:
# mean
print(torch.mean(e))
# mean along columns

print(torch.mean(e,dim=0))

tensor(5.)
tensor([7.0000, 5.5000, 2.5000])


In [48]:
# median

print(torch.median(e))

tensor(5.)


In [49]:
# max and min

print(torch.max(e))

print(torch.min(e))

tensor(9.)
tensor(0.)


In [50]:
# product

print(torch.prod(e))

tensor(0.)


In [51]:
# std dev

print(torch.std(e))

tensor(3.0332)


In [52]:
# variance

print(torch.var(e))

tensor(9.2000)


In [55]:
# argmax and argmin

print(torch.argmax(e))
print(torch.argmin(e))

tensor(0)
tensor(2)


#### 4.Matrix operations

In [56]:
f = torch.randint(size=(2,3),low = 0,high = 10)
g = torch.randint(size=(3,2),low = 0 ,high =10)

In [57]:
print(f)
print(g)

tensor([[9, 9, 7],
        [5, 9, 8]])
tensor([[9, 7],
        [9, 2],
        [6, 7]])


In [58]:
# matrix multiplication

torch.matmul(f,g)

tensor([[204, 130],
        [174, 109]])

In [59]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [60]:
# transpose
print(f)
print("after transpose :")
torch.transpose(f,0,1)

tensor([[9, 9, 7],
        [5, 9, 8]])
after transpose :


tensor([[9, 5],
        [9, 9],
        [7, 8]])

In [62]:
h = torch.randint(size=(3,3),low =0 ,high=10,dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [63]:
# determinant
torch.det(h)

tensor(-6.)

In [64]:
# inverse

torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

#### 5. comparison operations

In [65]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [66]:
# greater than
print(i>j)
# less than
print(i<j)
# eqaul to
print(i==j)
# not equal to
print(i!=j)
# greater than equal to
print(i>=j)
# less than equal to
print(i<=j)


tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])


#### 6 .special functions

In [73]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [74]:
# log

torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [75]:
# exponent

torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [76]:
# sqrt

torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [77]:
# sigmoid

torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [78]:
# softmax

torch.softmax(k,dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [79]:
# relu

torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

#### 7. Inpace operations

In [80]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [81]:
m+n

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [82]:
m.add_(n) # for permanent changes in m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [83]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [84]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [85]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [86]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [87]:
m.relu_() # for permanent changes in m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [88]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

#### 8 .copying a tensor

In [90]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [91]:
b =a

In [92]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [93]:
a[0][0]=0

In [94]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [95]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [96]:
c = a.clone()

In [97]:
c

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [98]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [99]:
a[0][0]=5

In [100]:
a

tensor([[5.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [101]:
c

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [102]:
id(a)

132928032785008

In [103]:
id(c)

132928033115968

#### 9 .Tensor operations on GPU

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creating tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.2365, 0.4597, 0.7482],
        [0.4862, 0.7514, 0.3861]], device='cuda:0')

In [6]:
# moving an existing tensor to gpu
x = torch.rand((2,3))
x

tensor([[0.2364, 0.8610, 0.6021],
        [0.2426, 0.7213, 0.0373]])

In [8]:
y=x.to(device)
y

tensor([[0.2364, 0.8610, 0.6021],
        [0.2426, 0.7213, 0.0373]], device='cuda:0')

In [9]:
y+5 # this operation is now running on gpu

tensor([[5.2364, 5.8610, 5.6021],
        [5.2426, 5.7213, 5.0373]], device='cuda:0')

In [11]:
import time

size =10000

# creating random matrix on cpu
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"total time taken on cpu to perform above calculations :{cpu_time:.4f} seconds")

# move matrix to gpu
matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')


# measure time on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() #ensure all gpu operation complete
gpu_time = time.time() - start_time

print(f"total time taken on gpu to perform above calculations :{gpu_time:4f} seconds")

# compare result

print("\nspeedup (cpu time / gpu time):",cpu_time/gpu_time)

total time taken on cpu to perform above calculations :16.0377 seconds
total time taken on gpu to perform above calculations :0.656639 seconds

speedup (cpu time / gpu time): 24.423933380413885


#### 10. Reshaping tensors

In [13]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [15]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
b = torch.rand(2,3,4)
b

tensor([[[0.5159, 0.3230, 0.8592, 0.9328],
         [0.0763, 0.1714, 0.2239, 0.2923],
         [0.7454, 0.2974, 0.5570, 0.5802]],

        [[0.3914, 0.5038, 0.1178, 0.9765],
         [0.0764, 0.4415, 0.5724, 0.5975],
         [0.7516, 0.3307, 0.8106, 0.5567]]])

In [17]:
# permute
b.permute(2,0,1)

tensor([[[0.5159, 0.0763, 0.7454],
         [0.3914, 0.0764, 0.7516]],

        [[0.3230, 0.1714, 0.2974],
         [0.5038, 0.4415, 0.3307]],

        [[0.8592, 0.2239, 0.5570],
         [0.1178, 0.5724, 0.8106]],

        [[0.9328, 0.2923, 0.5802],
         [0.9765, 0.5975, 0.5567]]])

In [18]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [19]:
# unsqueeze
# image
c = torch.rand(226,226,3)
c.unsqueeze(0)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [20]:
# squeeze

d = torch.rand(1,10)
d.squeeze(0)

tensor([0.4705, 0.1175, 0.6467, 0.2562, 0.8721, 0.9007, 0.8462, 0.2463, 0.5776,
        0.7092])

#### 11 . Numpy and Pytorch

In [21]:
import numpy as np

In [22]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [23]:
b = a.numpy()
b

array([1, 2, 3])

In [24]:
type(b)

numpy.ndarray

In [25]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [26]:
torch.from_numpy(c)

tensor([1, 2, 3])